name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ "main" ]   # builds only when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push image to ACR
        uses: azure/acr-build@v1
        with:
          service-principal: ${{ secrets.AZURE_CREDENTIALS }}
          registry: kisanshaktiacr.azurecr.io
          repository: harvest-worker
          image: latest
