name: Build and Push Harvest Worker to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name kisanshaktiacr

      - name: Build and push Docker image
        run: |
          docker build -t kisanshaktiacr.azurecr.io/harvest-worker:latest ./ndvi-harvest-worker
          docker push kisanshaktiacr.azurecr.io/harvest-worker:latest
